# Generated by Django 4.0.4 on 2022-05-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='sex',
            field=models.CharField(default='Male', max_length=30),
        ),
    ]
