# Generated by Django 4.0.4 on 2022-05-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0002_employees_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeservice',
            name='membership',
            field=models.CharField(choices=[('Association', 'Association'), ('Union', 'Union'), ('Neutral', 'Neutral')], default='Neuatral', max_length=30),
        ),
    ]
