# Generated by Django 4.0.4 on 2022-05-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0003_alter_employeeservice_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='sex',
            field=models.CharField(default='M', max_length=30),
        ),
    ]
