# Generated by Django 4.0.4 on 2022-05-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0004_alter_employees_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevote',
            name='deshabhimani_sub',
            field=models.CharField(default='No Sub', max_length=30),
        ),
    ]
