# Generated by Django 4.0.4 on 2022-06-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0006_employees_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevote',
            name='subscription_amount',
            field=models.CharField(max_length=20),
        ),
    ]
