# Generated by Django 4.0.4 on 2022-06-05 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0007_alter_employeevote_subscription_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='adddress',
            new_name='address',
        ),
    ]
