# Generated by Django 4.0.4 on 2022-06-06 11:27

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0008_rename_adddress_employees_address'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employeeservice',
            managers=[
                ('dashboard', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='employeevote',
            managers=[
                ('dashboard', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='employeeservice',
            name='date_of_entry',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employeeservice',
            name='date_of_retire',
            field=models.DateField(null=True),
        ),
    ]
