# Generated by Django 4.0.4 on 2022-06-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0011_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activity',
            field=models.CharField(max_length=100),
        ),
    ]
