# Generated by Django 4.0.4 on 2022-06-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0012_alter_activities_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
