# Generated by Django 4.0.4 on 2022-06-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0013_activities_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionsUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=30)),
            ],
        ),
    ]
