# Generated by Django 4.0.4 on 2022-06-13 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0014_sectionsunits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='SectionsUnits',
        ),
        migrations.AddField(
            model_name='employeeservice',
            name='unit',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactsapp.unit'),
        ),
        migrations.AlterField(
            model_name='employeeservice',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactsapp.section'),
        ),
    ]
