# Generated by Django 4.0.4 on 2022-06-13 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0015_section_unit_delete_sectionsunits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeservice',
            name='department',
        ),
        migrations.AddField(
            model_name='employeeservice',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contactsapp.section'),
            preserve_default=False,
        ),
    ]
