# Generated by Django 4.0.4 on 2022-06-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0016_remove_employeeservice_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeservice',
            name='section',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
