# Generated by Django 4.0.4 on 2022-06-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0017_alter_employeeservice_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeservice',
            old_name='section',
            new_name='department',
        ),
    ]
