# Generated by Django 4.0.4 on 2022-06-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0018_rename_section_employeeservice_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
