# Generated by Django 4.0.4 on 2022-06-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0019_remove_section_unit_delete_unit'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employeeservice',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='employeeservice',
            name='unit',
        ),
    ]
