# Generated by Django 4.0.4 on 2022-06-13 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0021_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contactsapp.unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.IntegerField(),
        ),
    ]
