# Generated by Django 4.0.4 on 2022-06-14 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0022_section_unit_alter_unit_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeservice',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contactsapp.section'),
        ),
    ]
