# Generated by Django 4.0.4 on 2022-06-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0023_alter_employeeservice_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeservice',
            name='department',
        ),
    ]
