# Generated by Django 4.0.4 on 2022-06-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0025_employeeservice_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeservice',
            name='exit_remark',
            field=models.CharField(default='Retired', max_length=50),
        ),
    ]
