# Generated by Django 4.0.4 on 2022-06-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0026_employeeservice_exit_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeservice',
            name='is_current_employee',
            field=models.BooleanField(default=True),
        ),
    ]
